### ISSUE TITLE
Errors when updating labels "this.github.issues.getLabels" is not a function

### ISSUE THREAD

**Issue by kevo1ution** [probot/settings#153]
I was integrating the settings bot with my own bot, and am getting the error `this.github.issues.getLabels` is not a function in `lib/plugins/labels.js:24.31`. 

I looked at the octokit/rest.js documentation and could not find a function for "issues.getLabels". Should it be `this.github.issues.listLabelsForRepo` (https://octokit.github.io/rest.js/#octokit-routes-issues-list-labels-for-repo) ?

**Comment by kevo1ution** [comment]
I also am having a similar error with milestones: `this.github.issues.getMilestones is not a function lib/plugins/milestones.js:17:42`

**Comment by travi** [comment]
thanks for the report. the `getLabels` issue has been [previously reported](https://github.com/probot/settings/pull/143), but a fix has been slowed as we discuss options around a similar problem with `updateLabel`. i've suggested splitting that PR so that we can get the `getLabels` fix in place. if you have any feedback on either piece of that PR, please feel free to comment there.

i imagine that the `getMilestones` issue that you are seeing is for a similar reason. if you'd be interested in tracking down the details and submitting a PR to fix, i'd be happy to help you through the details to get this resolved.

**Comment by kevo1ution** [comment]
@travi I created a PR for the `getMilestones` issue. I'm not sure if I did it correctly, as this is my first time.
