### ISSUE TITLE
handle various versions of api attributes for label names

### ISSUE THREAD

**Issue by travi** [probot/settings#167]
this is a follow up for https://github.com/probot/settings/pull/143 fo more forgiving backwards and forwards compatibility with api changes related to label names. as mentioned in https://github.com/probot/settings/pull/143#issuecomment-547227363, deciding a long-term strategy for handling this properly was delaying integration of the fix in that PR, so it was decided to handle this separately.

we may want to handle each of the attribute versions so that all are mapped to the current attribute when the call is made. we may also want to consider a recommended attribute for the config that is more abstracted from the api call and accounts for the timing differences between the config file for the settings app, which has a fairly long life, and the actual api call, which references a specific point in time when the call is made. this timing difference could introduce confusion when trying to understand which term refers to the old value and which refers to the new value (see conversation in https://github.com/probot/settings/pull/143 for additional discussion)

**Comment by elstudio** [comment]
Any thoughts on how we should handle renaming of labels?

As #407 says, updating label names does not work the way it’s documented in `settings.yml`.

Rather than `name` and `oldname` attributes, the API now expects something like this:

```yaml
labels:
  - name: the old/current name of an existing label we want to change
    new_name: the updated label name
``` 

Details of the GitHub API change that precipitated this are here https://github.com/probot/settings/pull/143#issuecomment-539307068, but in short, to rename a label, we must now provide `name` and `new_name` attributes.

If you specify a `new_name` attribute in your `settings.yml` the current code just about works. So we could update the README and call it a day.

Should we worry about any sort of backwards compatibility for folks with `oldname` in their settings.yml files?

Maybe no, because renaming labels is a one-time activity?

As for the bigger question behind this issue — do we need some sort of shim/adapter between the format of `settings.yml` and the GitHub API?

API changes like this are intended to be rare, so maybe no, too?
