### ISSUE TITLE
Consider allowing to use .yaml instead of .yml as file extension

### ISSUE THREAD

**Issue by localheinz** [probot/settings#213]
According to [Wikipedia](https://en.wikipedia.org/wiki/YAML), the

> ... official recommended filename extension for YAML files has been `.yaml` since 2006.

Last time I checked, it was not possible to use `.yml` as file extension for the [configuration file](https://github.com/probot/settings#usage).

GitHub Actions allows to use `.yaml` files.

I'm aware that this is probably not a very important issue, and I'm aware that this might cause issues, such as

- what should be done when people provide both `.github/settings.yml` and `.github/settings.yaml`

but I'm a bit curious - have you considered allowing users to use `.yaml` as file extension?

**Comment by JoseThen** [comment]
This is valid, I just encountered this issue when testing `probot/settings` out, I thought it was not working, when it was just my extension was wrong.

**Comment by travi** [comment]
since settings simply uses probot's [context.config](https://probot.github.io/api/latest/classes/context.html#config), it would probably be more appropriate to [open the issue against probot itself](https://github.com/probot/probot/issues/new/choose).

both are common extensions, and i don't personally have a strong opinion on this. i think it can be acceptable to document the expected filename, like we have, and follow the convention that is common to many other probot apps, but i can see the value of falling back to the alternative.

i think it would be more beneficial to make the decision consistently across probot apps if a change were to be made, though.

**Comment by JoseThen** [comment]
This makes sense thank you!

**Comment by travi** [comment]
thanks. i'll close this one for now, but feel free to reference a probot issue here, if you end up opening one

**Comment by localheinz** [comment]
Thank you, @JoseThen and @travi!

I have opened a corresponding issue at https://github.com/probot/probot/issues/1162.

**Comment by micimize** [comment]
protobot/protobot kicked responsibility back to app developers https://github.com/probot/probot/issues/1162#issuecomment-741052772

**Comment by wheelerlaw** [comment]
I think this is really just a couple-liner change in this repo, the `context.config` method takes the filename as an argument, so it could look for the `.yml` extension and if it doesn't exist then look for the `.yaml` one. 

The changes would likely take place [here](https://github.com/repository-settings/app/blob/67bfd136dd24b9f110db009aa03ab2a9f2b918e3/index.js#L8):

```js
  async function syncSettings (context, repo = context.repo()) {
    const config = await context.config('settings.yml', {}, { arrayMerge: mergeArrayByName })
    return Settings.sync(context.octokit, repo, config)
  }
```
