### ISSUE TITLE
Add support for data services (vulnerability alerts and the dependency graph )

### ISSUE THREAD

**Issue by timReynolds** [probot/settings#230]
## Prerequisites:

The github UI allows for "Data services" these include dependency graph and security alerts which are exposed by the API https://developer.github.com/v3/repos/#enable-vulnerability-alerts
 
## New Feature

These should be added as options in the yaml file so they can automatically be set.

**Comment by travi** [comment]
would you mind filling out the rest of the template? many of the features that are missing here are because the necessary resources are not available for update through the api. while i agree that having this available here would be very valuable, helping us understand if this is available through the api would help a lot in deciding how realistic it is to get this added.
