### ISSUE TITLE
feature: add config for requiring-a-linear-commit-history

### ISSUE THREAD

**Issue by timomayer** [probot/settings#292]
## New Feature

make this feature configurable with the settings bot:
https://docs.github.com/en/github/administering-a-repository/requiring-a-linear-commit-history

**Comment by travi** [comment]
this should already be available through the branch protection capabilities (the `branches` section of `settings.yml` file). as mentioned in our README, the full api docs for that functionality are available here: https://developer.github.com/v3/repos/branches/#update-branch-protection and show `required_linear_history` as the property that you would need to set.

is this not working for you? there are some bits about branch protection that have to be set very specifically, so be sure to confirm that branch protection is working otherwise and then include that property.

**Comment by travi** [comment]
i just confirmed that this is working on my test repository. for an example of configuring it, please refer to this commit: https://github.com/travi-test/settings-test/commit/0000a457ccb85cb24c423d6d9f4759989da4a8cc
