### ISSUE TITLE
Open issue when yaml parsing fails

### ISSUE THREAD

**Issue by patcon** [probot/settings#84]
Re-ticketed from https://github.com/probot/settings/issues/83#issuecomment-381715248

Would this be a good idea?

**Comment by JasonEtco** [comment]
Nod to https://github.com/probot/probot/issues/299 and https://github.com/probot/friction/issues/11 where we talked about Probot Core having some functionality to report errors (probably via issues). This gets a little dicey, since then every single Probot app would need `Issue read/write`. I think there are some other issues/places where we've elaborated and I can't find them right now 🤔

**Comment by jwsloan** [comment]
What if there was either a config yml validator site, or possibly a specific app that watches for changes to config files, and comments on PRs involving them? Or puts in Issues for ones that exist already when the app is installed.

**Comment by patcon** [comment]
@jwsloan is that last idea worth capturing in probot/ideas, so it doesn't languish here? It seems like a really great app idea imho!

**Comment by jwsloan** [comment]
Gotta love the Stale bot. I had forgotten about that comment. :)

I'll add it to probot ideas.

**Comment by jwsloan** [comment]
I started a branch to get `tcbyrd/probot-report-error` brought in for this, and catching just about any other error. Definitely still on my radar.
